name: Build Unsigned iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ldid

      - name: Build, sign and package IPA
        run: .github/scripts/build-and-package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-iOS-App
          path: output/MASTestApp-unsigned.ipa
